* About TextMagic Python API
  The TextMagic Python API includes classes and methods
  for accessing the functionality of the [[https://www.textmagic.com/docs/api/][TextMagic REST API]].
* Installing
  The easiest way to install the TextMagic Python API is via =pip=:

  #+begin_example
    pip install textmagic
  #+end_example

  You can also install the package manually:

  #+begin_example
    git clone git@github.com:textmagic/textmagic-rest-python.git
    cd textmagic-python
    python setup.py install
  #+end_example
* Usage
  The first thing to do is create a =TextmagicRestClient= object:

  #+begin_src python
    from textmagic.rest import TextmagicRestClient
    client = TextmagicRestClient("username", "API key")
  #+end_src

  You will, of course, need to provide your own username and API key.

  To send an SMS message:

  #+begin_src python
    client.messages.create(phones="comma-separated list of phone numbers", text="message text")
  #+end_src

  You can send to multiple phone numbers by separating them by a comma.
* Building the Documentation
  Sphinx document is provided in the =doc= directory.
  Building the documentation is as simple as runing =make html=, =make latexpdf=, etc.
  If you are are using =virtualenv=, you may need to tweak the make file
  to use =sphinx-build= from your =virtualenv=.
  Alternatively, you could use =sphinx-build= directly.
